<?php

namespace Franklin\BlogBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BlogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlogRepository extends EntityRepository
{
	public function findAllDesc() 
	{

		$em = $this->getEntityManager();

		$dql = 'SELECT o
				FROM BlogBundle:Blog o
				ORDER BY o.id DESC';

		$consulta = $em->createQuery($dql);
		
		$result = $consulta->getResult();
        return $result;

	}

	public function findBlogsPublicados() 
	{

		$fechaAtencion = new \DateTime();
		$fechaAtencion->format('Y-m-d H:i:s');

		$em = $this->getEntityManager();

		$dql = 'SELECT o
				FROM BlogBundle:Blog o
				WHERE o.fechaProgramada <= :fecha
				ORDER BY o.id DESC';

		$consulta = $em->createQuery($dql);
		$consulta->setParameter('fecha', $fechaAtencion);
		
		$result = $consulta->getResult();
        return $result;

	}

	public function findBlogsPublicadosPorLocale($locale) 
	{

		$fechaAtencion = new \DateTime();
		$fechaAtencion->format('Y-m-d H:i:s');

		$em = $this->getEntityManager();

		$dql = 'SELECT o
				FROM BlogBundle:Blog o
				WHERE o.fechaProgramada <= :fecha
				AND o.locale = :locale
				ORDER BY o.id DESC';

		$consulta = $em->createQuery($dql);
		$consulta->setParameter('fecha', $fechaAtencion);
		$consulta->setParameter('locale', $locale);
		
		$result = $consulta->getResult();
        return $result;

	}

	public function findLastMonthBlogs($numberOfLastPosts)
	{
		$em = $this->getEntityManager();

		$dql = 'SELECT o
				FROM BlogBundle:Blog o
				ORDER BY o.id DESC';

		$consulta = $em->createQuery($dql);
		$consulta->setMaxResults($numberOfLastPosts);

		
		$result = $consulta->getResult();
        return $result;
	}

	public function findLastMonthBlogsPorLocale($numberOfLastPosts, $locale)
	{
		$em = $this->getEntityManager();

		$dql = 'SELECT o
				FROM BlogBundle:Blog o
				WHERE o.locale = :locale
				ORDER BY o.id DESC';

		$consulta = $em->createQuery($dql);
		$consulta->setParameter('locale', $locale);
		$consulta->setMaxResults($numberOfLastPosts);

		
		$result = $consulta->getResult();
        return $result;
	}
}
