<?php

namespace Franklin\AdminBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use Symfony\Component\HttpFoundation\File\File;

use Pagerfanta\Adapter\ArrayAdapter;
use Pagerfanta\Pagerfanta;

use Franklin\PortadaBundle\Entity\Servicio;

use Franklin\PortadaBundle\Form\Type\ServicioType;


class ServiciosController extends Controller
{
	public function serviciosAction($page)
    {
    	$em = $this->getDoctrine()->getManager();
        $servicios = $em->getRepository('PortadaBundle:Servicio')->findAllDesc();

        $adapter = new ArrayAdapter($servicios);
        $pager = new Pagerfanta($adapter);
        $pager->setMaxPerPage(5);
        $pager->setCurrentPage($page);

        return $this->render('AdminBundle:Servicios:servicios.html.twig', array(
            'servicios' => $pager->getCurrentPageResults(),
            'pager' => $pager,
        ));
    }

    public function newAction(Request $request)
    {
        $em = $this->getDoctrine()->getManager();
        $servicio = new Servicio();
        $form = $this->createForm(new ServicioType(), $servicio);

        if ($request->isMethod('POST')) {
            $form->bind($request);
            if ($form->isValid()) {

                $em->persist($servicio);
                $em->flush();

                $flashBag = $this->get('session')->getFlashBag();
                $flashBag->add('primary', 'Se ha guardado exitosamente el nuevo servicio');
                return $this->redirect($this->generateUrl('admin_servicios'));
            }
        }

        // echo "<div>";
        // \Doctrine\Common\Util\Debug::dump($caso->getComentario());
        // echo '</div>';

        return $this->render('AdminBundle:Servicios:new.html.twig', array(
            'form' => $form->createView()
        ));

    }

    public function editAction(Request $request, $id)
    {
        $em = $this->getDoctrine()->getManager();

        //Setters
        $servicio = $em->getRepository('PortadaBundle:Servicio')->find($id);
        $form = $this->createForm(new ServicioType(), $servicio);

        if ($request->isMethod('POST')) {
            $form->bind($request);
            if ($form->isValid()) {

                $em->persist($servicio);
                $em->flush();

                $flashBag = $this->get('session')->getFlashBag();
                $flashBag->add('primary', 'Se ha editado exitosamente el servicio');
                return $this->redirect($this->generateUrl('admin_servicios'));
            }
        }


        return $this->render('AdminBundle:Servicios:edit.html.twig', array(
            'form' => $form->createView(),
            'id' => $id,
            'servicio' => $servicio
        ));
    }

    /**
     * @return string
     */
    private function generateUniqueFileName()
    {
        // md5() reduces the similarity of the file names generated by
        // uniqid(), which is based on timestamps
        return md5(uniqid());
    }
}