<?php

namespace Franklin\UsuariosBundle\Entity;

/**
 * NewsletterlistRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsletterlistRepository extends \Doctrine\ORM\EntityRepository
{
}
