<?php

namespace Franklin\UsuariosBundle\Entity;

/**
 * Paciente
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PacienteRepository extends \Doctrine\ORM\EntityRepository
{
	public function findNewsletterActive() 
	{

		$em = $this->getEntityManager();

		$dql = 'SELECT o
				FROM UsuariosBundle:Paciente o
				WHERE o.isSubscribed = true
				ORDER BY o.id DESC';

		$consulta = $em->createQuery($dql);
		
		$result = $consulta->getResult();
        return $result;

	}
}
