security:
    providers:
        in_memory: { memory: ~ }

    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    firewalls:
        main:
            pattern: ^/
            anonymous:    true

    access_control:
        - { path: ^/, role: IS_AUTHENTICATED_ANONYMOUSLY }

    role_hierarchy:
        ROLE_USER:     ROLE_USER