security:
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                default_target_path: admin_dashboard
            logout:
                 path:   fos_user_security_logout
            anonymous:    true
            remember_me:
                 key:      "%secret%"
                 lifetime: 2592000
                 path:     /
                 domain:   ~
                 user_provider: fos_userbundle

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/confirmed, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, role: ROLE_ADMIN }
        

    role_hierarchy:
        ROLE_USER:     ROLE_USER
        ROLE_ADMIN:    [ROLE_ADMIN, ROLE_USER]
        ROLE_FRANKLIN: [ROLE_USER, ROLE_ADMIN, ROLE_FRANKLIN]