admin_dashboard:
    path:     /dashboard
    defaults: { _controller: AdminBundle:Default:dashboard }

admin_profile:
    path:     /profile
    defaults: { _controller: AdminBundle:Default:profile }

admin_blog:
    pattern:  /blog
    defaults: { _controller: AdminBundle:Default:blog , page: 1 }
    requirements:
        _method:  GET

admin_blog_paginated:
    pattern:  /blog/{page}
    defaults: { _controller: AdminBundle:Default:blog }
    requirements:
        _method:  GET



admin_review:
    pattern:  /review
    defaults: { _controller: AdminBundle:Review:reviews, page: 1 }
    requirements:
        _method:  GET

admin_review_paginated:
    pattern:  /review/{page}
    defaults: { _controller: AdminBundle:Review:reviews }
    requirements:
        _method:  GET

review_new:
    path:     /new/review
    defaults: { _controller: AdminBundle:Review:new }

review_edit:
    path:     /edit/review/{id}
    defaults: { _controller: AdminBundle:Review:edit }



admin_mails:
    path:     /mails
    defaults: { _controller: AdminBundle:Default:mails, page: 1 }
    requirements:
        _method:  GET

admin_mails_paginated:
    pattern:  /mails/{page}
    defaults: { _controller: AdminBundle:Default:mails }
    requirements:
        _method:  GET

newsletter_prepare:
    path:     /prepare/newsletter/{numberOfLastPosts}
    defaults: { _controller: AdminBundle:Newsletter:prepare, numberOfLastPosts: 6 }

newsletter_test:
    path:     /test/newsletter/{numberOfLastPosts}/{email}/{subject}
    defaults: { _controller: AdminBundle:Newsletter:test, numberOfLastPosts: 6, email: "", subject: "" }

newsletter_send:
    path:     /send/newsletter/{numberOfLastPosts}/{subject}
    defaults: { _controller: AdminBundle:Newsletter:send, numberOfLastPosts: 6, subject: "" }


admin_casos:
    pattern:  /casos
    defaults: { _controller: AdminBundle:Casos:casos, page: 1 }
    requirements:
        _method:  GET

admin_casos_paginated:
    pattern:  /casos/{page}
    defaults: { _controller: AdminBundle:Casos:casos }
    requirements:
        _method:  GET

caso_new:
    path:     /new/caso
    defaults: { _controller: AdminBundle:Casos:new }

caso_edit:
    path:     /edit/caso/{id}
    defaults: { _controller: AdminBundle:Casos:edit }


admin_feedback:
    pattern:  /feedback
    defaults: { _controller: AdminBundle:Feedback:feedback, page: 1 }
    requirements:
        _method:  GET

admin_feedback_paginated:
    pattern:  /feedback/{page}
    defaults: { _controller: AdminBundle:Feedback:feedback }
    requirements:
        _method:  GET

feedback_new:
    path:     /new/feedback
    defaults: { _controller: AdminBundle:Feedback:new }

feedback_edit:
    path:     /edit/feedback/{id}
    defaults: { _controller: AdminBundle:Feedback:edit }


admin_pacientes:
    pattern:  /pacientes
    defaults: { _controller: AdminBundle:Paciente:pacientes, page: 1 }
    requirements:
        _method:  GET

admin_pacientes_paginated:
    pattern:  /pacientes/{page}
    defaults: { _controller: AdminBundle:Paciente:pacientes }
    requirements:
        _method:  GET

paciente_new:
    path:     /new/paciente
    defaults: { _controller: AdminBundle:Paciente:new }

paciente_edit:
    path:     /edit/paciente/{id}
    defaults: { _controller: AdminBundle:Paciente:edit }


admin_invitaciones:
    pattern:  /invitaciones
    defaults: { _controller: AdminBundle:Invitacion:invitaciones, page: 1 }
    requirements:
        _method:  GET

admin_invitaciones_paginated:
    pattern:  /invitaciones/{page}
    defaults: { _controller: AdminBundle:Invitacion:invitaciones }
    requirements:
        _method:  GET

invitacion_new:
    path:     /new/invitacion
    defaults: { _controller: AdminBundle:Invitacion:new }

invitacion_new_paciente:
    path:     /new/invitacion/paciente/{id}
    defaults: { _controller: AdminBundle:Invitacion:new }

invitacion_edit:
    path:     /edit/invitacion/{id}
    defaults: { _controller: AdminBundle:Invitacion:edit }