admin_dashboard:
    path:     /dashboard
    defaults: { _controller: AdminBundle:Default:dashboard }

admin_profile:
    path:     /profile
    defaults: { _controller: AdminBundle:Default:profile }

admin_blog:
    pattern:  /blog
    defaults: { _controller: AdminBundle:Default:blog , page: 1 }
    requirements:
        _method:  GET

admin_blog_paginated:
    pattern:  /blog/{page}
    defaults: { _controller: AdminBundle:Default:blog }
    requirements:
        _method:  GET



admin_review:
    pattern:  /review
    defaults: { _controller: AdminBundle:Review:reviews, page: 1 }
    requirements:
        _method:  GET

admin_review_paginated:
    pattern:  /review/{page}
    defaults: { _controller: AdminBundle:Review:reviews }
    requirements:
        _method:  GET

review_new:
    path:     /new/review
    defaults: { _controller: AdminBundle:Review:new }

review_edit:
    path:     /edit/review/{id}
    defaults: { _controller: AdminBundle:Review:edit }



admin_mails:
    path:     /mails
    defaults: { _controller: AdminBundle:Default:mails }

newsletter_prepare:
    path:     /prepare/newsletter/{numberOfLastPosts}
    defaults: { _controller: AdminBundle:Newsletter:prepare, numberOfLastPosts: 6 }

newsletter_test:
    path:     /test/newsletter/{numberOfLastPosts}/{email}/{subject}
    defaults: { _controller: AdminBundle:Newsletter:test, numberOfLastPosts: 6, email: "", subject: "" }

newsletter_send:
    path:     /send/newsletter/{numberOfLastPosts}/{subject}
    defaults: { _controller: AdminBundle:Newsletter:send, numberOfLastPosts: 6, subject: "" }


admin_casos:
    pattern:  /casos
    defaults: { _controller: AdminBundle:Casos:casos, page: 1 }
    requirements:
        _method:  GET

admin_casos_paginated:
    pattern:  /casos/{page}
    defaults: { _controller: AdminBundle:Casos:casos }
    requirements:
        _method:  GET

caso_new:
    path:     /new/caso
    defaults: { _controller: AdminBundle:Casos:new }

caso_edit:
    path:     /edit/caso/{id}
    defaults: { _controller: AdminBundle:Casos:edit }