<?php

namespace Franklin\PortadaBundle\Entity;

/**
 * DescripcionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DescripcionRepository extends \Doctrine\ORM\EntityRepository
{
}
