portada_homepage:
    path:     /{_locale}
    defaults: { _controller: PortadaBundle:Default:index, _locale: es }
    requirements:
        _locale: es|pt|en|it

portada_locale:
    path:     /locale/{_locale}
    defaults: { _controller: PortadaBundle:Default:locale }

portada_servicio:
    path:     /{_locale}/{slug}
    defaults: { _controller: PortadaBundle:Default:servicio, _locale: es }
    requirements:
        _locale: es|pt|en|it

portada_send_message:
    path:     /send-message/{name}/{email}/{message}
    defaults: { _controller: PortadaBundle:Default:sendMessage }

portada_vcard:
    path:     /md/vcard/
    defaults: { _controller: PortadaBundle:Default:vcard }

portada_privacy:
    path:     /privacy-policy
    defaults: { _controller: PortadaBundle:Default:privacy }

portada_terms:
    path:     /terms-of-service
    defaults: { _controller: PortadaBundle:Default:terms }

portada_well_one:
    path:     /.well-known/acme-challenge/ftz5S_nrfG4rlzMQiVpLdQpW1hRzLXBufHmEZ-l1IKw
    defaults: { _controller: PortadaBundle:Default:wellOne }

portada_well_two:
    path:     /.well-known/acme-challenge/F12a0688p1nPpfJx-nMUDbOCaIFu0JhMx9lyvVNhvys
    defaults: { _controller: PortadaBundle:Default:wellTwo }