portada_homepage:
    path:     /{_locale}
    defaults: { _controller: PortadaBundle:Default:index, _locale: es }
    requirements:
        _locale: es|pt|en|it

portada_locale:
    path:     /locale/{_locale}
    defaults: { _controller: PortadaBundle:Default:locale }

portada_servicio:
    path:     /{_locale}/{slug}
    defaults: { _controller: PortadaBundle:Default:servicio, _locale: es }
    requirements:
        _locale: es|pt|en|it

portada_send_message:
    path:     /send-message/{name}/{email}/{message}
    defaults: { _controller: PortadaBundle:Default:sendMessage }

portada_cert1:
    path:    /.well-known/acme-challenge/A7Zp1nUG3uJf9-WPaBObf0mM3PuqbGlV0E9DU7_kEbI
    defaults: { _controller: PortadaBundle:Default:cert1 }

portada_cert2:
    path:    /.well-known/acme-challenge/9ut4IQYS_GZMZR2K2jQo46H1-fZgRX3sOpRj0kLxwQg
    defaults: { _controller: PortadaBundle:Default:cert2 }

portada_vcard:
    path:     /md/vcard/
    defaults: { _controller: PortadaBundle:Default:vcard }

portada_privacy:
    path:     /privacy-policy
    defaults: { _controller: PortadaBundle:Default:privacy }

portada_terms:
    path:     /terms-of-service
    defaults: { _controller: PortadaBundle:Default:terms }