portada_homepage:
    path:     /{_locale}
    defaults: { _controller: PortadaBundle:Default:index, _locale: es }
    requirements:
        _locale: es|pt|en|it

portada_locale:
    path:     /locale/{locale}
    defaults: { _controller: PortadaBundle:Default:locale }

portada_servicio:
    path:     /{servicio}/{_locale}
    defaults: { _controller: PortadaBundle:Default:servicio, _locale: es }
    requirements:
        _locale: es|pt|en|it

portada_send_message:
    path:     /send-message/{name}/{email}/{message}
    defaults: { _controller: PortadaBundle:Default:sendMessage }

portada_vcard:
    path:     /md/vcard/
    defaults: { _controller: PortadaBundle:Default:vcard }