portada_homepage:
    path:     /{_locale}
    defaults: { _controller: PortadaBundle:Default:index, _locale: es }
    requirements:
        _locale: es|pt|en|it

portada_locale:
    path:     /locale/{_locale}
    defaults: { _controller: PortadaBundle:Default:locale }

portada_servicio:
    path:     /{_locale}/{slug}
    defaults: { _controller: PortadaBundle:Default:servicio, _locale: es }
    requirements:
        _locale: es|pt|en|it

portada_send_message:
    path:     /send-message/{name}/{email}/{message}
    defaults: { _controller: PortadaBundle:Default:sendMessage }

portada_cert1:
    path:    /.well-known/acme-challenge/4I_CMZnJB9sG2fpKnEofKc66mxuvjurxx58jQhzEq2g
    defaults: { _controller: PortadaBundle:Default:cert1 }

portada_cert2:
    path:    /.well-known/acme-challenge/8kKgLHzNo6azsvAsY5WEf_wmQYFPzg_u-5s03r8vnHQ
    defaults: { _controller: PortadaBundle:Default:cert2 }

portada_vcard:
    path:     /md/vcard/
    defaults: { _controller: PortadaBundle:Default:vcard }

portada_privacy:
    path:     /privacy-policy
    defaults: { _controller: PortadaBundle:Default:privacy }

portada_terms:
    path:     /terms-of-service
    defaults: { _controller: PortadaBundle:Default:terms }