blog_homepage:
    path:     /{_locale}/blogs
    defaults: { _controller: BlogBundle:Default:index, page: 1, _locale: es  }
    requirements:
        _method:  GET
        _locale: es|pt|en|it

blog_homepage_paginated:
    pattern:  /{_locale}/blogs/{page}
    defaults: { _controller: BlogBundle:Default:index, _locale: es }
    requirements:
        _method:  GET
        _locale: es|pt|en|it

blog_view:
    path:     /{_locale}/blogs/view/{slug}
    defaults: { _controller: BlogBundle:Default:view, _locale: es  }
    requirements:
        _locale: es|pt|en|it

blog_new:
    path:     /franklin-alvear/new/blog
    defaults: { _controller: BlogBundle:Default:new }

blog_edit:
    path:     /franklin-alvear/edit/blog/{id}
    defaults: { _controller: BlogBundle:Default:edit }